### ISSUE TITLE
insert tagged photos in list view and leave user photos in grid view

### ISSUE THREAD

**Issue by legacychimera247** [wiktorek140/Prostogram#10]
one thing missing from the app, is the ability to see photos where people are tagged in (3rd tab on instagram on user page : grid > list > tagged)

it would be nice if we could have users photos on the grid in profile page and have photos where people are tagged in, in the list view (the one you access by tapping on the right arrow near the username)

**Comment by wiktorek140** [comment]
if u can provide me how its look on android app/page i can try to implement this

**Comment by legacychimera247** [comment]
ok...here it is...this is how it look on android...i have no photos where i'm tagged in but you get the idea
https://1drv.ms/i/s!AlyMkCypv00qgsR8v-GaEzduvqJESQ
as you know prostogram as a brief set of your last photos in the profile page and you should tap on the arrow to have the complete feed...what i propose is to move all the photos on the profile page and move photos where i am tagged in (or other users are tagged) to the feed on the arrow like my screen show
https://1drv.ms/i/s!AlyMkCypv00qgsR9B_qlvt0Sf0eV3A
(all the tagged photos would be moved here https://1drv.ms/i/s!AlyMkCypv00qgsR-QLRq-L_IPWT7zA )

**Comment by legacychimera247** [comment]
i just found out a screen for this function from sailgrande, the app which prostogram is based from...now sailgrande is broken and not accessible anymore but it may give you some ideas...

https://1drv.ms/i/s!AlyMkCypv00qgsR_aBlH-u1clky-_w

**Comment by wiktorek140** [comment]
Little other idea but work i thing like in instagram on android. need to be tested
