### ISSUE TITLE
two icons doing the same thing on the same screen

### ISSUE THREAD

**Issue by legacychimera247** [wiktorek140/Prostogram#11]
just noticed that pressing on your profile icon and pressing on the last icon on the right just do the exactly same thing, they take you to your personale profile page...don't know...maybe one of them could be used for another thing...just thinking anyway...

**Comment by wiktorek140** [comment]
i thing its normal reaction. if in android its work other than there just write where it move/ what is showed

**Comment by legacychimera247** [comment]
ok so...this is how it look on android
https://1drv.ms/i/s!AlyMkCypv00qgsR60qjRChqgJrGOtA
and this is how it looks in sailfish
https://1drv.ms/i/s!AlyMkCypv00qgsR7LnY0Fx1744q4Rw

i don't really have an idea on what to do but since we have 2 button dong the same thing i tought it was possible to use one of the icons for doing something different...just guessing anyway eh :)
