### ISSUE TITLE
tags and user photos overlapping

### ISSUE THREAD

**Issue by legacychimera247** [wiktorek140/Prostogram#16]
as you may see tags and user photos are overlapping...here's a screen...

https://1drv.ms/i/s!AlyMkCypv00qgsUAjCFkx4jjbi4F8Q

**Comment by wiktorek140** [comment]
yea, i see whats the point. but can u click tag button? if yes it only cosmetic fix

**Comment by legacychimera247** [comment]
well the arrow it's clickable so it's only cosmetic i assume...but anyway the tag section always gives an error so i assume is broken or simply not working yet...
