### ISSUE TITLE
sometimes videos are not playables and hang the application

### ISSUE THREAD

**Issue by legacychimera247** [wiktorek140/Prostogram#17]
well here the title says it all...it happens i enter a profile, play a video and the video keeps loading forever...if i exit the vides the app hangs asking me to wait or kill...sometimes it even happen than a video on the home might crash the app...

**Comment by wiktorek140** [comment]
@legacychimera247 i have no clue what cause it but probably there is a bug/incorrect initialized variable which one break playing video

**Comment by legacychimera247** [comment]
don't know...just reporting you bugs :)
