### ISSUE TITLE
comments not working

### ISSUE THREAD

**Issue by legacychimera247** [wiktorek140/Prostogram#23]
the new comment system seems quite good, but it's not working at all. If i press the send button simply nothing happen...

**Comment by wiktorek140** [comment]
fixed

**Comment by legacychimera247** [comment]
Thanks, would have closed myself but was busy :)

Il Martedì 28 agosto 2018, Wiktor Strzębała scrive:
> fixed
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.￼

-- 
Inviato dal mio Jolla
