### ISSUE TITLE
can't log out from the app 

### ISSUE THREAD

**Issue by legacychimera247** [wiktorek140/Prostogram#28]
well the title explain it all, if i press the log out button simply nothing happen and next time i will open the app I'm still logged on my profile...

**Comment by wiktorek140** [comment]
It will be fixed in next release, 0.9.10. 
And if u can, please report every bugs, color errors, placement errors, and size errors if u have display resolution at least HD or higher

**Comment by legacychimera247** [comment]
I will nicely do that :)

Il Domenica 9 settembre 2018, Wiktor Strzębała scrive:
> It will be fixed in next release, 0.9.10.
> And if u can, please report every bugs, color errors, placement errors, and size errors if u have display resolution at least HD or higher
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.￼

-- 
Inviato dal mio Jolla

**Comment by wiktorek140** [comment]
Done
