### ISSUE TITLE
impossible to know who posted a story

### ISSUE THREAD

**Issue by legacychimera247** [wiktorek140/Prostogram#8]
as you may have seen it's quite impossible to know who posted a story since they are shown by a preview of the story and they are accessible only from the home view...it would be nice if profile picture from user is shown insted of story preview, and it would be even nice to have stories in the classic instagram mode (eg by tapping on a user profile image in personal profile). if it's not possible to highlith a user picture (like instagram does) it may just be possible to insert some counter to show there are new stories :)

**Comment by wiktorek140** [comment]
Done
